import { createIndexedDbFileSystem, INDEXED_DB_DEFAULT_NAME } from './indexedDbFileSystem';

type LazyFileProvider = () => Promise<string>;
type InitialFileValue =
    | string
    | Uint8Array
    | { content?: string | Uint8Array; mode?: number; mtime?: Date }
    | LazyFileProvider;
type InitialFilesMap = Record<string, InitialFileValue>;

type IndexedDbFsOptions = {
    dbName?: string;
    initialFiles?: InitialFilesMap;
    ensureDirectories?: string[];
};

const fsByDbName = new Map();
const defaultFilesSeedPromiseByDbName = new Map<string, Promise<void>>();

const DEFAULT_SKILLS_BASE_URLS = ['/public/skills', '/skills'];

function getSkillsBaseUrls() {
    const origin =
        typeof globalThis !== 'undefined' && globalThis.location?.origin
            ? globalThis.location.origin
            : '';
    const baseUrls = DEFAULT_SKILLS_BASE_URLS;
    if (!origin) return baseUrls;
    const normalizedOrigin = origin.replace(/\/$/, '');
    return baseUrls.map(baseUrl => `${normalizedOrigin}${baseUrl}`);
}

/**
 * Fetches the skills manifest generated by tools/scripts/generate_default_skill_content.js.
 * Returns the list of relative paths (e.g. "salesforce/soql.SKILL.md").
 * Falls back to an empty array on any error so a network hiccup never breaks the app.
 */
async function fetchSkillManifest(): Promise<string[]> {
    for (const baseUrl of getSkillsBaseUrls()) {
        try {
            const res = await fetch(`${baseUrl}/skill.manifest.json`);
            if (!res.ok) continue;
            const data = await res.json();
            if (Array.isArray(data?.skills)) {
                return data.skills as string[];
            }
        } catch {
            // Try the next runtime asset location.
        }
    }
    return [];
}

function buildFileProvidersFromRelativePaths(relativePaths) {
    const prefixes = getSkillsBaseUrls();
    const files = {};
    for (const rel of relativePaths) {
        if (!rel) continue;
        const bashPath = `/workspace/skills/${rel}`;
        files[bashPath] = async () => {
            for (const prefix of prefixes) {
                const url = `${prefix}/${rel}`;
                try {
                    const res = await fetch(url);
                    if (res.ok) return res.text();
                } catch {
                    // Try the next runtime asset location.
                }
            }
            throw new Error(`Failed to load skill file: ${rel}`);
        };
    }
    return files as Record<string, LazyFileProvider>;
}

function getParentDirectoriesForFilePaths(filePaths) {
    const out = new Set();
    const addParents = fullPath => {
        const raw = String(fullPath || '');
        if (!raw.startsWith('/')) return;
        const parts = raw.split('/').filter(Boolean);
        if (parts.length <= 1) return;
        // Treat last segment as file name.
        const dirParts = parts.slice(0, -1);
        let current = '';
        for (const part of dirParts) {
            current += `/${part}`;
            out.add(current);
        }
    };
    (filePaths || []).forEach(addParents);
    return Array.from(out).sort((a, b) => a.length - b.length);
}

function seedDefaultFilesIfNeeded(fs, dbName): Promise<void> {
    const existing = defaultFilesSeedPromiseByDbName.get(dbName);
    if (existing) return existing;

    // Async best-effort seed; never blocks app boot.
    const seedPromise = (async () => {
        try {
            await fs.ready;

            // Discover skill paths from the generated manifest (assets/skills/skill.manifest.json).
            const skillPaths = await fetchSkillManifest();
            const coreDefaultFiles = buildFileProvidersFromRelativePaths(skillPaths);
            const coreEnsureDirs = getParentDirectoriesForFilePaths(Object.keys(coreDefaultFiles));

            // Repair: older versions could have created empty placeholder files under
            // `/workspace/skills/...`, which then prevents registering lazy providers (no overwrite).
            // If the default skill file exists but is empty, delete it so the lazy loader can work.
            for (const skillPath of Object.keys(coreDefaultFiles)) {
                const existing = await fs.getEntry(skillPath).catch(() => null);
                const isEmptyFile =
                    existing &&
                    existing.type === 'file' &&
                    ((typeof existing.size === 'number' && existing.size === 0) ||
                        !existing.contentBase64);
                if (isEmptyFile) {
                    await fs.rm(skillPath, { force: true }).catch(() => {});
                }
            }
            for (const dir of coreEnsureDirs) {
                await fs.mkdir(dir, { recursive: true }).catch(() => {});
            }
            await fs.registerInitialFiles(coreDefaultFiles);
        } catch (_) {
            // ignore seeding failures (offline, blocked fetch, etc.)
        }
    })();
    defaultFilesSeedPromiseByDbName.set(dbName, seedPromise);
    return seedPromise;
}

function mergeEnsureDirectories(ensureDirectories, initialFiles) {
    const dirs = new Set(['/workspace', '/workspace/skills']);
    (ensureDirectories || []).forEach(d => dirs.add(d));
    const parents = getParentDirectoriesForFilePaths(Object.keys(initialFiles || {}));
    parents.forEach(d => dirs.add(d));
    return Array.from(dirs);
}

function createSingletonFs(options: IndexedDbFsOptions = {}) {
    const { dbName = INDEXED_DB_DEFAULT_NAME, initialFiles = {}, ensureDirectories } = options;
    const mergedInitialFiles = { ...(initialFiles || {}) };
    const fs = createIndexedDbFileSystem({
        dbName,
        initialFiles: mergedInitialFiles,
        ensureDirectories: mergeEnsureDirectories(ensureDirectories, mergedInitialFiles),
    });
    fsByDbName.set(dbName, fs);
    seedDefaultFilesIfNeeded(fs, dbName);
    return fs;
}

export function getIndexedDbFileSystem(options: IndexedDbFsOptions = {}) {
    const { dbName = INDEXED_DB_DEFAULT_NAME, initialFiles = {}, ensureDirectories } = options;
    const existing = fsByDbName.get(dbName);
    if (!existing) {
        return createSingletonFs({ dbName, initialFiles, ensureDirectories });
    }

    // Ensure default files are available on the singleton (best-effort, no overwrite).
    seedDefaultFilesIfNeeded(existing, dbName);

    if (initialFiles && Object.keys(initialFiles).length > 0) {
        existing.registerInitialFiles(initialFiles).catch(() => {});
    }

    if (ensureDirectories && ensureDirectories.length > 0) {
        for (const dir of ensureDirectories) {
            existing.mkdir(dir, { recursive: true }).catch(() => {});
        }
    }

    return existing;
}

export async function ensureIndexedDbDefaultFiles(
    options: Pick<IndexedDbFsOptions, 'dbName'> = {}
) {
    const { dbName = INDEXED_DB_DEFAULT_NAME } = options;
    const fs = getIndexedDbFileSystem({ dbName });
    await seedDefaultFilesIfNeeded(fs, dbName);
}
