import DOMPurify from 'dompurify';

import { LINK_PROTOCOLS, MARKDOWN_ATTRIBUTES, MARKDOWN_TAGS } from './constants';

export function isSafeMarkdownLink(value: string): boolean {
    if (!value || /[\u0000-\u0020\u007f]/.test(value)) return false;
    if (value.startsWith('#')) return true;
    if (value.startsWith('/') && !value.startsWith('//') && !value.includes('\\')) return true;
    try {
        const url = new URL(value);
        return LINK_PROTOCOLS.has(url.protocol) && !url.username && !url.password;
    } catch {
        return false;
    }
}

export function isSafeMarkdownImage(value: string, allowRemoteImages: boolean): boolean {
    if (/^data:image\/(png|jpeg|gif|webp);base64,[a-z0-9+/=]+$/i.test(value)) return true;
    if (value.startsWith('blob:')) return true;
    // Permit local assets, but never protocol-relative or backslash URLs.
    if (allowRemoteImages && /^\/(?!\/)/.test(value) && !/[\\\u0000-\u0020]/.test(value))
        return true;
    return allowRemoteImages && /^https?:\/\//i.test(value) && isSafeMarkdownLink(value);
}

/** Sanitize at the final HTML boundary, including attributes generated by Markdown. */
export function sanitizeMarkdownHtml(html: string, allowRemoteImages = true): string {
    const fragment = DOMPurify.sanitize(html, {
        ALLOWED_TAGS: MARKDOWN_TAGS,
        ALLOWED_ATTR: MARKDOWN_ATTRIBUTES,
        ALLOW_DATA_ATTR: false,
        ALLOW_ARIA_ATTR: false,
        // Custom Workbench links are checked again below. This is never a blanket protocol bypass.
        ALLOWED_URI_REGEXP:
            /^(?:(?:https?|mailto|sftoolkit|sfrecord|sfobject|blob):|data:image\/(?:png|jpeg|gif|webp);base64,|\/|#)/i,
        RETURN_DOM_FRAGMENT: true,
    });
    for (const anchor of Array.from(fragment.querySelectorAll('a'))) {
        if (!isSafeMarkdownLink(anchor.getAttribute('href') || '')) anchor.removeAttribute('href');
        anchor.setAttribute('rel', 'noopener noreferrer');
    }
    for (const image of Array.from(fragment.querySelectorAll('img'))) {
        if (!isSafeMarkdownImage(image.getAttribute('src') || '', allowRemoteImages)) {
            image.replaceWith(
                fragment.ownerDocument.createTextNode(
                    image.getAttribute('alt') || '[Image blocked]'
                )
            );
        } else {
            image.setAttribute('referrerpolicy', 'no-referrer');
        }
    }
    const container = fragment.ownerDocument.createElement('div');
    container.appendChild(fragment);
    return container.innerHTML;
}

/** Diagrams may contain SVG but must not introduce HTML or external resource loads. */
export function sanitizeDiagramSvg(svg: string): string {
    return DOMPurify.sanitize(svg, {
        USE_PROFILES: { svg: true, svgFilters: true },
        FORBID_TAGS: ['foreignObject', 'image', 'a', 'style'],
        FORBID_ATTR: ['style', 'href', 'xlink:href'],
        ALLOW_DATA_ATTR: false,
    });
}
